package com.pojo;

// Generated Oct 1, 2019 1:24:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * Publication generated by hbm2java
 */
public class Publication implements java.io.Serializable {

	private Integer pid;
	private Author author;
	private Book book;
	private String pname;
	private String pprice;
	private String paddress;
	private String pemail;
	private String pphone;
	private String pdate;

	public Publication() {
	}

	public Publication(Author author, Book book, String pname, String pprice, String paddress, String pemail,
			String pphone, String pdate) {
		this.author = author;
		this.book = book;
		this.pname = pname;
		this.pprice = pprice;
		this.paddress = paddress;
		this.pemail = pemail;
		this.pphone = pphone;
		this.pdate = pdate;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getPprice() {
		return this.pprice;
	}

	public void setPprice(String pprice) {
		this.pprice = pprice;
	}

	public String getPaddress() {
		return this.paddress;
	}

	public void setPaddress(String paddress) {
		this.paddress = paddress;
	}

	public String getPemail() {
		return this.pemail;
	}

	public void setPemail(String pemail) {
		this.pemail = pemail;
	}

	public String getPphone() {
		return this.pphone;
	}

	public void setPphone(String pphone) {
		this.pphone = pphone;
	}

	public String getPdate() {
		return this.pdate;
	}

	public void setPdate(String pdate) {
		this.pdate = pdate;
	}

}
